services:
  auth:
    image: auth
    build: back_end/auth/
    container_name: auth
    ports:
      - "3000:3000"
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL_CONTAINER}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - transcendance-net
    depends_on:
      logstash:
        condition: service_healthy

  user-management:
    image: user-management
    build: back_end/user_management/
    container_name: user-management
    ports:
      - "3002:3002"
    restart: always
    env_file:
      - .env
    networks:
      - transcendance-net

  tournament:
    image: tournament
    build: back_end/tournament/
    container_name: tournament
    ports:
      - "3003:3003"
    restart: always
    env_file:
      - .env
    networks:
      - transcendance-net

  database:
    image: database
    build: back_end/database/
    container_name: database
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - db_storage:/var/lib/postgresql/data
    networks:
      - transcendance-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./back_end/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - transcendance-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3004:3000"
    networks:
      - transcendance-net
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3004/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - transcendance-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.8.2
    container_name: logstash
    volumes:
      - ./back_end/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      - HTTP_HOST=0.0.0.0
      - HTTP_PORT=9600
    depends_on:
      - elasticsearch
    networks:
      - transcendance-net
    healthcheck:
      test: ["CMD", "curl", "-s", "--fail", "http://localhost:9600"]
      interval: 5s
      timeout: 3s
      retries: 10


  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - transcendance-net

  vault:
    image: vault
    build: back_end/vault
    container_name: vault
    volumes:
      - ${HOME}/vault:/vault
    networks:
      - transcendance-net
    env_file:
      - .env
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_ROOT_TOKEN}
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    command: vault server -dev
    healthcheck:
      test: ["CMD", "curl", "-s", "--fail", "http://localhost:8200/v1/sys/health"]
      interval: 5s
      timeout: 2s
      retries: 10
    ports:
      - "8200:8200"

  waf:
    image: waf
    build: back_end/modsecurity
    container_name: waf
    volumes:
      - ./back_end/modsecurity/modsecurity.conf:/etc/modsecurity/modsecurity.conf
      - ./back_end/modsecurity/nginx.conf:/usr/local/nginx/conf/nginx.conf
      - ./back_end/modsecurity/crs:/etc/modsecurity/crs
      - ./back_end/modsecurity/ssl:/etc/nginx/ssl
      - ${HOME}/vault:/vault
    ports:
      - "8443:443"
    depends_on:
      - auth
      - vault
    networks:
      - transcendance-net
    entrypoint: ./entrypoint.sh

  front_end:
    image: front_end
    build: front_end/
    container_name: front_end
    ports:
      - "5173:5173"
    networks:
      - transcendance-net

volumes:
  grafana-storage: {}
  db_storage: {}
  elasticsearch_data: {}

networks:
  transcendance-net:
    name: transcendance-net
    driver: bridge