services:
  auth:
    image: auth
    build: auth/
    container_name: auth
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    networks:
      - transcendance-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - transcendance-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3004:3000"
    networks:
      - transcendance-net
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}

networks:
  transcendance-net:
    name: transcendance-net
    driver: bridge